import { IntakeData } from './types';
import { mergeTemplate } from './merge';
import { generatePDF } from './pdf';
import { generateDOCX } from './docx';

// Enhanced template content for each document type
const UNA_AGREEMENT_TEMPLATE = `# UNINCORPORATED NONPROFIT ASSOCIATION AGREEMENT

**Document Type:** UNA Formation Agreement  
**State:** {{entityState}}  
**Generated:** ${new Date().toLocaleDateString()}  
**Platform:** UNA Formation Done Right

---

## ARTICLE I: ORGANIZATION IDENTITY

### Section 1.1: Entity Name
**Official Name:** {{entityName}}

### Section 1.2: Purpose and Mission
**Primary Purpose:** {{entityPurpose}}

**Core Activities:** {{entityActivities}}

**Formation State:** {{entityState}}

**Effective Date:** {{entityStartDate}}

---

## ARTICLE II: ORGANIZER INFORMATION

### Section 2.1: Primary Organizer
**Name:** {{organizerName}}  
**Role:** {{organizerRole}}  
**Email:** {{organizerEmail}}  
**Phone:** {{organizerPhone}}  
**Address:** {{organizerAddress}}, {{organizerCity}}, {{organizerState}} {{organizerZip}}

---

## ARTICLE III: ORGANIZATIONAL ADDRESS

### Section 3.1: Mailing Address
**Official Mailing Address:** {{mailingAddress}}, {{mailingCity}}, {{mailingState}} {{mailingZip}}, {{mailingCountry}}

---

## ARTICLE IV: GOVERNANCE STRUCTURE

### Section 4.1: Leadership Framework
**Organizational Structure:** {{leadershipStructure}}

**Family Leadership Considerations:** {{familyLeadership}}

**Conflict of Interest Policies:** {{conflictOfInterest}}

**Succession Planning:** {{successionPlanning}}

---

## ARTICLE V: FINANCIAL AND OPERATIONAL PLANS

### Section 5.1: Property and Assets
**Property Plans:** {{propertyPlans}}

### Section 5.2: Funding and Revenue
**Grant Plans:** {{grantPlans}}

**Fundraising Activities:** {{fundraisingPlans}}

---

## ARTICLE VI: TAX AND COMPLIANCE

### Section 6.1: EIN Requirements
**EIN Required:** {{needsEIN}}

**Tax-Exempt Intent:** {{taxExemptIntent}}

**Fiscal Sponsorship Arrangements:** {{fiscalSponsorship}}

### Section 6.2: Operational Scope
**Interstate Activity:** {{interstateActivity}}

**States of Operation:** {{statesOfOperation}}

**Compliance Notes:** {{complianceNotes}}

---

## ARTICLE VII: ORGANIZATIONAL IDENTITY

### Section 7.1: Insignia and Branding
**Has Organizational Insignia:** {{hasInsignia}}

**Insignia Description:** {{insigniaDescription}}

---

## ARTICLE VIII: EXECUTION

### Section 8.1: Signatures
**Organizer Signature:** {{organizerSignature}}  
**Date:** {{organizerSignatureDate}}

**Witness Signature:** {{witnessSignature}}  
**Date:** {{witnessSignatureDate}}

---

## ARTICLE IX: EFFECTIVE DATE AND TERM

This agreement establishes the Unincorporated Association known as **{{entityName}}** and shall be effective as of **{{entityStartDate}}**.

**Note:** This agreement is designed to comply with California UNA formation requirements. For legal compliance and risk management, consider consulting with legal professionals for complex organizational structures or high-risk activities.

---

*Generated by UNA Formation Done Right - Professional UNA Formation Services*`;

const EIN_GUIDE_TEMPLATE = `# EMPLOYER IDENTIFICATION NUMBER (EIN) REGISTRATION GUIDE

**Organization:** {{entityName}}  
**Organizer:** {{organizerName}}  
**Contact:** {{organizerEmail}} | {{organizerPhone}}  
**Generated:** ${new Date().toLocaleDateString()}  
**Platform:** UNA Formation Done Right

---

## OVERVIEW

An Employer Identification Number (EIN) is required for your UNA to open bank accounts, hire employees, and file tax returns. This guide provides step-by-step instructions for obtaining your EIN.

---

## STEP 1: EIN REQUIREMENTS ASSESSMENT

**EIN Required:** {{needsEIN}}

**Note:** EINs are required for UNAs that will:
- Open bank accounts
- Hire employees
- File tax returns
- Apply for grants or funding
- Operate under fiscal sponsorship

---

## STEP 2: APPLICATION METHODS

### Option A: Online Application (Recommended)
**Website:** [IRS EIN Application Portal](https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online)

**Advantages:**
- Immediate processing
- No fees
- 24/7 availability
- Instant EIN assignment

**Requirements:**
- Valid SSN or ITIN
- U.S. address
- Business information ready

### Option B: Mail Application
**Form:** SS-4 (Application for Employer Identification Number)
**Processing Time:** 4-6 weeks
**Address:** Internal Revenue Service, Cincinnati, OH 45999

### Option C: Fax Application
**Form:** SS-4
**Processing Time:** 4 business days
**Fax:** (855) 641-6935

---

## STEP 3: INFORMATION REQUIRED

**Organization Details:**
- Legal name: {{entityName}}
- Mailing address: {{mailingAddress}}, {{mailingCity}}, {{mailingState}} {{mailingZip}}
- Type of entity: Unincorporated Association
- State of formation: {{entityState}}

**Organizer Information:**
- Name: {{organizerName}}
- SSN or ITIN
- Address: {{organizerAddress}}, {{organizerCity}}, {{organizerState}} {{organizerZip}}
- Phone: {{organizerPhone}}

**Business Information:**
- Principal business activity: {{entityActivities}}
- Date business started: {{entityStartDate}}
- Number of employees: 0 (initially)

---

## STEP 4: APPLICATION PROCESS

### Online Application Steps:
1. **Access the IRS EIN Portal**
2. **Select Entity Type:** "Nonprofit Organization"
3. **Enter Organization Information**
4. **Provide Organizer Details**
5. **Review and Submit**
6. **Receive EIN Immediately**

### Important Notes:
- Keep your EIN secure and confidential
- Use the same EIN for all business activities
- Update IRS if organizational information changes
- EINs are permanent and cannot be cancelled

---

## STEP 5: POST-APPLICATION

### Immediate Actions:
- Save your EIN confirmation
- Update your UNA Agreement with EIN
- Begin bank account application process

### Next Steps:
- Apply for bank accounts
- Set up financial tracking systems
- Consider tax-exempt status if applicable
- Establish compliance monitoring

---

## COMPLIANCE REMINDERS

**Tax Filing Requirements:**
- Annual information returns may be required
- Maintain accurate financial records
- Keep organizational documents current

**Professional Guidance:**
For complex tax situations or compliance questions, consider consulting with:
- Certified Public Accountant (CPA)
- Tax attorney specializing in nonprofits
- Nonprofit compliance consultant

---

*This guide is provided for informational purposes. For legal compliance and risk management, consider consulting with qualified professionals.*

---

*Generated by UNA Formation Done Right - Professional UNA Formation Services*`;

const LP_UNA_128_TEMPLATE = `# LP/UNA-128 FILING PACKAGE

## For: {{entityName}}

**Organizer:** {{organizerName}}
**Contact Email:** {{organizerEmail}}
**Contact Phone:** {{organizerPhone}}

## California LP/UNA-128 Form Instructions

### Form Purpose
The LP/UNA-128 form is required for California-based Unincorporated Associations that:
- Operate in California
- Have a mailing address in California
- Conduct business activities in California

### Filing Requirements
**Entity Name:** {{entityName}}
**State of Formation:** {{entityState}}
**Mailing Address:** {{mailingAddress}}, {{mailingCity}}, {{mailingState}} {{mailingZip}}

### Step-by-Step Filing Process

#### 1. Form Preparation
- **Form Type:** LP/UNA-128
- **Filing Fee:** $20 (check or money order payable to "Secretary of State")
- **Processing Time:** 2-3 weeks

#### 2. Required Information
- **Section 1:** Entity Information
  - Name: {{entityName}}
  - Type: Unincorporated Association
  - Date of formation: {{entityStartDate}}

- **Section 2:** Mailing Address
  - Street: {{mailingAddress}}
  - City: {{mailingCity}}
  - State: {{mailingState}}
  - ZIP: {{mailingZip}}

- **Section 3:** Organizer Information
  - Name: {{organizerName}}
  - Role: {{organizerRole}}
  - Address: {{organizerAddress}}, {{organizerCity}}, {{organizerState}} {{organizerZip}}

#### 3. Filing Methods

##### Option A: Mail Filing (Recommended)
**Address:** Secretary of State, Business Entities Filings, P.O. Box 944225, Sacramento, CA 94244-2250

**Include:**
- Completed LP/UNA-128 form
- $20 filing fee
- Self-addressed stamped envelope for return

##### Option B: In-Person Filing
**Address:** 1500 11th Street, Sacramento, CA 95814
**Hours:** Monday-Friday, 8:00 AM - 5:00 PM

#### 4. Post-Filing Steps
1. **Save Confirmation:** Keep the filed form and receipt
2. **Update Records:** Add filing confirmation to entity records
3. **Compliance:** Maintain compliance with California requirements
4. **Renewal:** No annual renewal required for LP/UNA-128

### 5. Important Notes
- **California Specific:** This form is only required for California operations
- **No Expiration:** LP/UNA-128 filing does not expire
- **Amendments:** File amendments if entity information changes
- **Compliance:** Maintain compliance with California nonprofit laws

### 6. Contact Information
**California Secretary of State:**
- **Phone:** 916-657-5448
- **Website:** [bizfile.sos.ca.gov](https://bizfile.sos.ca.gov)
- **Email:** businessentities@sos.ca.gov

### 7. Additional Resources
- [California Nonprofit Law](https://leginfo.legislature.ca.gov/)
- [Secretary of State Forms](https://www.sos.ca.gov/business-programs/business-entities/forms/)
- [Nonprofit Compliance Guide](https://www.sos.ca.gov/business-programs/business-entities/)

---

*This filing package is prepared for {{entityName}} based on the information provided during intake.*`;

// Helper function to download a Uint8Array
export function downloadBlob(data: Uint8Array, filename: string, mimeType: string): void {
  console.log('downloadBlob called with:', { filename, mimeType, dataSize: data.length });
  
  try {
    if (mimeType === 'application/pdf') {
      // For PDFs, we'll open in a new tab for printing
      const blob = new Blob([data], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      
      // Open in new tab for printing
      const newWindow = window.open(url, '_blank');
      if (newWindow) {
        // Wait a moment for the page to load, then show print dialog
        setTimeout(() => {
          newWindow.print();
        }, 1000);
      }
      
      // Clean up URL after a delay
      setTimeout(() => URL.revokeObjectURL(url), 5000);
      
    } else {
      // For other file types, use normal download
      const blob = new Blob([data], { type: mimeType });
      console.log('Blob created:', blob.size, 'bytes');
      
      const url = URL.createObjectURL(blob);
      console.log('URL created:', url);
      
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      console.log('Download link added to DOM');
      
      a.click();
      console.log('Download link clicked');
      
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      console.log('Cleanup completed');
    }
  } catch (error) {
    console.error('Error in downloadBlob:', error);
    throw error;
  }
}

// Generate UNA Agreement document
export async function generateUnaAgreement(data: IntakeData): Promise<Uint8Array> {
  try {
    console.log('Starting UNA Agreement generation...');
    console.log('Input data:', data);
    
    // Merge template with data
    const mergedContent = mergeTemplate(UNA_AGREEMENT_TEMPLATE, data);
    console.log('Merged content length:', mergedContent.length);
    console.log('First 200 chars of merged content:', mergedContent.substring(0, 200));
    
    // Generate PDF
    console.log('Calling generatePDF...');
    const pdfData = await generatePDF(mergedContent, `${data.entityName} - UNA Agreement`);
    console.log('PDF generated, size:', pdfData.length);
    
    return pdfData;
  } catch (error) {
    console.error('Error generating UNA Agreement:', error);
    throw new Error('Failed to generate UNA Agreement. Please try again.');
  }
}

// Generate EIN Registration Guide
export async function generateEinGuide(data: IntakeData): Promise<Uint8Array> {
  try {
    // Merge template with data
    const mergedContent = mergeTemplate(EIN_GUIDE_TEMPLATE, data);
    
    // Generate PDF
    const pdfData = await generatePDF(mergedContent, `${data.entityName} - EIN Registration Guide`);
    
    return pdfData;
  } catch (error) {
    console.error('Error generating EIN Guide:', error);
    throw new Error('Failed to generate EIN Registration Guide. Please try again.');
  }
}

// Generate Comprehensive Formation Guide for California users
export async function generateComprehensiveGuide(data: IntakeData): Promise<Uint8Array> {
  try {
    console.log('Starting comprehensive guide generation...');
    console.log('Input data:', data);
    
    const template = `# COMPREHENSIVE UNA FORMATION GUIDE

## For: {{entityName}}

**Organizer:** {{organizerName}}  
**Contact Email:** {{organizerEmail}}  
**Contact Phone:** {{organizerPhone}}  
**State of Formation:** {{entityState}}  
**Date Prepared:** {{createdAt}}

---

# PART 1: UNA AGREEMENT

## Article I: Name and Purpose

**Entity Name:** {{entityName}}

**Purpose:** {{entityPurpose}}

**Primary Activities:** {{entityActivities}}

**State of Formation:** {{entityState}}

**Effective Date:** {{entityStartDate}}

## Article II: Organizer Information

**Organizer Name:** {{organizerName}}  
**Organizer Role:** {{organizerRole}}  
**Organizer Email:** {{organizerEmail}}  
**Organizer Phone:** {{organizerPhone}}  
**Organizer Address:** {{organizerAddress}}, {{organizerCity}}, {{organizerState}} {{organizerZip}}

## Article III: Mailing Address

**Mailing Address:** {{mailingAddress}}, {{mailingCity}}, {{mailingState}} {{mailingZip}}, {{mailingCountry}}

## Article IV: Governance Structure

**Leadership Structure:** {{leadershipStructure}}

**Family Leadership:** {{familyLeadership}}  
**Conflict of Interest:** {{conflictOfInterest}}

**Succession Planning:** {{successionPlanning}}

## Article V: Financial and Property Plans

**Property Plans:** {{propertyPlans}}

**Grant Plans:** {{grantPlans}}

**Fundraising Plans:** {{fundraisingPlans}}

## Article VI: Tax and Compliance

**EIN Required:** {{needsEIN}}  
**EIN Purpose:** {{einPurpose}}

**Tax-Exempt Intent:** {{taxExemptIntent}}  
**Fiscal Sponsorship:** {{fiscalSponsorship}}

**Interstate Activity:** {{interstateActivity}}  
**States of Operation:** {{statesOfOperation}}

**Compliance Notes:** {{complianceNotes}}

## Article VII: Insignia

**Has Insignia:** {{hasInsignia}}  
**Insignia Description:** {{insigniaDescription}}

## Article VIII: Signatures

**Organizer Signature:** {{organizerSignature}}  
**Organizer Signature Date:** {{organizerSignatureDate}}

**Witness Signature:** {{witnessSignature}}  
**Witness Signature Date:** {{witnessSignatureDate}}

---

# PART 2: LP/UNA-128 FILING GUIDE

## California LP/UNA-128 Form Instructions

### Form Purpose
The LP/UNA-128 form is required for California-based Unincorporated Associations that:
- Operate in California
- Have a mailing address in California
- Conduct business activities in California

### Filing Requirements
**Entity Name:** {{entityName}}  
**State of Formation:** {{entityState}}  
**Mailing Address:** {{mailingAddress}}, {{mailingCity}}, {{mailingState}} {{mailingZip}}

### Step-by-Step Filing Process

#### 1. Form Preparation
- **Form Type:** LP/UNA-128
- **Filing Fee:** $20 (check or money order payable to "Secretary of State")
- **Processing Time:** 2-3 weeks

#### 2. Required Information
- **Section 1:** Entity Information
  - Name: {{entityName}}
  - Type: Unincorporated Association
  - Date of formation: {{entityStartDate}}

- **Section 2:** Mailing Address
  - Street: {{mailingAddress}}
  - City: {{mailingCity}}
  - State: {{mailingState}}
  - ZIP: {{mailingZip}}

- **Section 3:** Organizer Information
  - Name: {{organizerName}}
  - Role: {{organizerRole}}
  - Address: {{organizerAddress}}, {{organizerCity}}, {{organizerState}} {{organizerZip}}

#### 3. Filing Methods

##### Option A: Mail Filing (Recommended)
**Address:** Secretary of State, Business Entities Filings, P.O. Box 944225, Sacramento, CA 94244-2250

**Include:**
- Completed LP/UNA-128 form
- $20 filing fee
- Self-addressed stamped envelope for return

##### Option B: In-Person Filing
**Address:** 1500 11th Street, Sacramento, CA 95814  
**Hours:** Monday-Friday, 8:00 AM - 5:00 PM

#### 4. Post-Filing Steps
1. **Save Confirmation:** Keep the filed form and receipt
2. **Update Records:** Add filing confirmation to entity records
3. **Compliance:** Maintain compliance with California requirements
4. **Renewal:** No annual renewal required for LP/UNA-128

### Contact Information
**California Secretary of State:**
- **Phone:** 916-657-5448
- **Website:** [bizfile.sos.ca.gov](https://bizfile.sos.ca.gov)
- **Email:** businessentities@sos.ca.gov

---

# PART 3: EIN APPLICATION GUIDE

## Step-by-Step EIN Application Process

### 1. Determine EIN Need
**EIN Required:** {{needsEIN}}  
**Purpose:** {{einPurpose}}

### 2. IRS Application Methods

#### Option A: Online Application (Recommended)
- **Website:** [IRS EIN Application](https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online)
- **Processing Time:** Immediate
- **Requirements:** Valid SSN or ITIN

#### Option B: Fax Application
- **Form:** SS-4
- **Fax Number:** 855-641-6935
- **Processing Time:** 4-7 business days

#### Option C: Mail Application
- **Form:** SS-4
- **Address:** Internal Revenue Service, Attn: EIN Operation, Cincinnati, OH 45999
- **Processing Time:** 4-6 weeks

### 3. Required Information
- Legal name of entity: **{{entityName}}**
- Mailing address: {{mailingAddress}}, {{mailingCity}}, {{mailingState}} {{mailingZip}}
- State of formation: {{entityState}}
- Principal business activity: {{entityPurpose}}
- Date business started: {{entityStartDate}}

### 4. Post-Application Steps
1. **Save EIN Confirmation:** Keep the EIN assignment letter
2. **Update Records:** Add EIN to all business documents
3. **Bank Account:** Use EIN to open business bank account
4. **Tax Filings:** Use EIN for all future tax returns

### Contact Information
**IRS EIN Support:** 800-829-4933  
**Hours:** Monday-Friday, 7:00 AM - 7:00 PM local time

---

# PART 4: DBA REGISTRATION GUIDE

## Doing Business As (DBA) Registration

### What is a DBA?
A DBA allows you to operate under a name different from your legal entity name. This is useful for:
- Marketing and branding
- Opening bank accounts
- Signing contracts
- Building public recognition

### California DBA Registration Process

#### 1. Check Name Availability
- **Search:** [California Secretary of State Business Search](https://bizfileonline.sos.ca.gov/search/business)
- **Verify:** Your desired DBA name is not already in use

#### 2. File Fictitious Business Name Statement
- **Form:** Fictitious Business Name Statement
- **Filing Fee:** $26
- **Where to File:** County Clerk's Office in your county

#### 3. Required Information
- **Entity Name:** {{entityName}}
- **DBA Name:** [Your desired business name]
- **Business Address:** {{mailingAddress}}, {{mailingCity}}, {{mailingState}} {{mailingZip}}
- **Business Type:** Unincorporated Association
- **Owner Information:** {{organizerName}}

#### 4. Publication Requirements
- **Publish:** In a general circulation newspaper in your county
- **Duration:** Once a week for 4 consecutive weeks
- **Proof:** Obtain affidavit of publication from newspaper

#### 5. Post-Filing Steps
1. **Keep Records:** Maintain filing confirmation and publication proof
2. **Update Documents:** Use DBA name on all business materials
3. **Renewal:** DBA expires after 5 years, file renewal

### County Clerk Offices
**Los Angeles County:** 213-974-5555  
**San Francisco County:** 415-554-4700  
**San Diego County:** 619-531-5500  
**Orange County:** 714-834-2500

---

# PART 5: BANK ACCOUNT OPENING GUIDE

## Opening a Business Bank Account

### Why You Need a Business Account
- **Separate Finances:** Keep business and personal funds separate
- **Professional Image:** Present a professional appearance to clients/donors
- **Tax Compliance:** Easier record keeping and tax preparation
- **Legal Protection:** Maintain limited liability protection

### Required Documents

#### 1. Entity Formation Documents
- **UNA Agreement:** Your completed and signed agreement
- **LP/UNA-128 Filing:** Confirmation from Secretary of State
- **EIN Confirmation:** IRS EIN assignment letter

#### 2. Organizer Information
- **Government ID:** Driver's license or passport
- **Social Security Number:** For background check
- **Proof of Address:** Utility bill or lease agreement

#### 3. Business Information
- **DBA Registration:** If operating under different name
- **Business Plan:** Brief description of activities
- **Expected Transactions:** Type and volume of banking activity

### Bank Selection Criteria

#### 1. Account Types
- **Business Checking:** For daily transactions
- **Business Savings:** For reserve funds
- **Merchant Services:** If accepting credit cards

#### 2. Fee Structure
- **Monthly Maintenance:** Usually $10-25/month
- **Transaction Fees:** Per-check or per-transaction charges
- **Minimum Balance:** Required to avoid fees

#### 3. Services Needed
- **Online Banking:** For remote account management
- **Mobile Deposits:** For check deposits
- **Bill Pay:** For recurring payments
- **Integration:** With accounting software

### Application Process

#### 1. Schedule Appointment
- **Call ahead:** Most banks require appointments for business accounts
- **Bring all documents:** Have everything ready
- **Prepare questions:** Ask about fees, services, and requirements

#### 2. Application Meeting
- **Complete forms:** Business account application
- **Provide documents:** All required paperwork
- **Discuss needs:** Explain your business activities
- **Set up services:** Online banking, debit cards, etc.

#### 3. Account Activation
- **Initial deposit:** Usually $100-500 minimum
- **Access setup:** Online banking credentials
- **Service activation:** Debit cards, checks, etc.

### Recommended Banks for Nonprofits
- **Chase Business:** Good online tools, many locations
- **Bank of America:** Strong nonprofit support
- **Wells Fargo:** Extensive branch network
- **Credit Unions:** Often lower fees, community-focused

---

# PART 6: FINANCIAL TRACKING SETUP

## Bookkeeping and Financial Management

### Setting Up Your Financial System

#### 1. Choose Accounting Software
**Recommended Options:**
- **QuickBooks Online:** $25/month, comprehensive features
- **Wave:** Free, good for small organizations
- **FreshBooks:** $15/month, user-friendly interface
- **Xero:** $12/month, strong reporting

#### 2. Chart of Accounts Setup
**Standard Categories:**
- **Income:** Donations, grants, program fees
- **Expenses:** Program costs, administrative, fundraising
- **Assets:** Bank accounts, equipment, property
- **Liabilities:** Loans, credit cards, accounts payable

#### 3. Document Organization
**File Structure:**
- **Invoices:** Numbered sequentially, stored by date
- **Receipts:** Categorized by expense type
- **Bank Statements:** Monthly, reconciled with books
- **Tax Documents:** Annual returns, supporting documents

### Best Practices

#### 1. Regular Reconciliation
- **Monthly:** Reconcile bank statements with accounting records
- **Quarterly:** Review financial reports and projections
- **Annually:** Prepare for tax filing and audits

#### 2. Expense Tracking
- **Categorize:** All expenses by program and type
- **Document:** Keep receipts and supporting documents
- **Approve:** Have approval process for significant expenses
- **Review:** Regular review of spending patterns

#### 3. Revenue Management
- **Track Sources:** Monitor different income streams
- **Project Cash Flow:** Plan for upcoming expenses
- **Diversify:** Don't rely on single funding source
- **Document:** All income with proper documentation

### Financial Reports

#### 1. Monthly Reports
- **Profit & Loss:** Income vs. expenses
- **Cash Flow:** Money coming in and going out
- **Balance Sheet:** Assets, liabilities, and equity

#### 2. Quarterly Reviews
- **Budget vs. Actual:** Compare planned vs. actual spending
- **Trend Analysis:** Identify patterns in income/expenses
- **Forecasting:** Project future financial needs

#### 3. Annual Reports
- **Tax Returns:** File appropriate tax forms
- **Financial Statements:** Prepare for stakeholders
- **Audit Preparation:** Organize records for review

### Compliance Requirements

#### 1. Tax Filing
- **Form 990-N:** If gross receipts < $50,000
- **Form 990-EZ:** If gross receipts $50,000-$200,000
- **Form 990:** If gross receipts > $200,000

#### 2. State Requirements
- **Annual Reports:** File with Secretary of State
- **Tax Returns:** State income tax if applicable
- **Sales Tax:** If selling goods or services

#### 3. Record Keeping
- **Retention:** Keep records for 7 years
- **Organization:** Maintain clear filing system
- **Access:** Ensure authorized people can access records

---

# PART 7: TIMELINE & CHECKLIST

## Formation Timeline

### Week 1: Initial Setup
- [ ] **Complete UNA Agreement** - Sign and date all copies
- [ ] **File LP/UNA-128** - Submit to California Secretary of State
- [ ] **Apply for EIN** - Complete IRS application online
- [ ] **Register DBA** - File with county clerk if needed

### Week 2-3: Banking & Setup
- [ ] **Open Business Bank Account** - Bring all required documents
- [ ] **Set Up Financial Tracking** - Choose and configure accounting software
- [ ] **Organize Documents** - Create filing system for all records
- [ ] **Set Up Online Banking** - Configure access and alerts

### Month 1: Operations
- [ ] **First Bank Deposits** - Transfer initial funds
- [ ] **Set Up Payment Systems** - Configure invoicing and payment processing
- [ ] **Establish Budget** - Create annual budget and spending plan
- [ ] **Insurance Review** - Assess liability and property insurance needs

### Month 2-3: Compliance
- [ ] **First Financial Reports** - Generate monthly P&L and cash flow
- [ ] **Tax Planning** - Consult with CPA about tax obligations
- [ ] **Compliance Review** - Ensure all filings are up to date
- [ ] **Policy Development** - Create financial policies and procedures

### Ongoing: Maintenance
- [ ] **Monthly Reconciliation** - Reconcile bank statements
- [ ] **Quarterly Reviews** - Review financial performance and projections
- [ ] **Annual Filings** - Complete required tax and compliance filings
- [ ] **Record Updates** - Keep all information current

## Priority Checklist

### High Priority (Do First)
1. **Sign UNA Agreement** - Legal foundation for your organization
2. **File LP/UNA-128** - Required for California recognition
3. **Get EIN** - Needed for banking and tax purposes
4. **Open Bank Account** - Essential for financial operations

### Medium Priority (Do Soon)
1. **Register DBA** - If operating under different name
2. **Set Up Accounting** - Establish financial tracking system
3. **Create Budget** - Plan your financial operations
4. **Get Insurance** - Protect against liability

### Lower Priority (Do Later)
1. **Develop Policies** - Create formal procedures
2. **Build Reserves** - Establish emergency funds
3. **Plan Growth** - Develop long-term financial strategy
4. **Professional Network** - Build relationships with advisors

---

# PART 8: RESOURCES & CONTACTS

## Key Contacts

### Government Agencies
- **California Secretary of State:** 916-657-5448
- **IRS Business Division:** 800-829-4933
- **County Clerk Offices:** Varies by county

### Professional Services
- **Legal Counsel:** For complex legal questions
- **CPA/Accountant:** For tax and accounting advice
- **Insurance Agent:** For liability and property coverage
- **Bank Officer:** For banking and financial services

### Online Resources
- **California SOS:** [bizfile.sos.ca.gov](https://bizfile.sos.ca.gov)
- **IRS Business:** [irs.gov/businesses](https://irs.gov/businesses)
- **Nonprofit Resources:** [calnonprofits.org](https://calnonprofits.org)

## Emergency Contacts

### Immediate Issues
- **Banking Problems:** Contact your bank's business services
- **Tax Questions:** Call IRS business support
- **Legal Issues:** Consult with attorney
- **Compliance Problems:** Contact Secretary of State

### Support Network
- **Gigi Stardust:** gigi@gigistardust.com
- **UNA Platform Support:** Available through platform
- **Community Groups:** Connect with other UNA organizers

---

*This comprehensive guide is prepared specifically for {{entityName}} based on the information provided during intake. It covers all essential steps for California UNA formation and operation. Keep this document for reference and update it as your organization evolves.*

**Prepared on:** {{createdAt}}  
**For:** {{entityName}}  
**By:** UNA Platform`;

    // Merge template with data
    console.log('Merging template with data...');
    const mergedContent = mergeTemplate(template, data);
    console.log('Template merged successfully, length:', mergedContent.length);
    console.log('First 500 chars of merged content:', mergedContent.substring(0, 500));
    
    // Generate PDF
    console.log('Calling generatePDF...');
    const pdfData = await generatePDF(mergedContent, `${data.entityName} - Comprehensive UNA Formation Guide`);
    console.log('PDF generated successfully, size:', pdfData.length);
    
    return pdfData;
  } catch (error) {
    console.error('Error generating Comprehensive Guide:', error);
    throw new Error('Failed to generate Comprehensive Guide. Please try again.');
  }
}

// Generate Out-of-State Guide for non-CA users
export async function generateOutOfStateGuide(data: IntakeData): Promise<Uint8Array> {
  try {
    const template = `# UNA FORMATION GUIDE FOR {{entityState}} RESIDENTS

## About This Platform

**Important Note:** This platform is specifically designed for California Unincorporated Association (UNA) formation. The documents, guidance, and filing requirements are optimized for California laws and regulations.

## What is a UNA?

An **Unincorporated Association (UNA)** is a flexible legal structure that allows groups to:
- Operate as a collective without formal incorporation
- Maintain tax-exempt status eligibility
- Have legal recognition for contracts and property
- Operate with minimal formal requirements

## Why California-Only?

California has specific UNA laws that:
- Provide clear legal recognition
- Allow for property ownership
- Support tax-exempt applications
- Have established filing procedures

Other states may have different laws or no UNA statutes at all.

## What You Can Do in {{entityState}}

### 1. Research Your State's Requirements
- **Visit your state's Secretary of State website**
- **Search for "Unincorporated Association" statutes**
- **Check for alternative legal structures** (LLC, Corporation, etc.)

### 2. Common State Variations
- **Some states have no UNA laws** - you may need to incorporate
- **Some states have different names** (e.g., "Unincorporated Association")
- **Some states require different filings** or have no filing requirements
- **Some states have different tax implications**

### 3. Alternative Legal Structures
If UNA formation isn't available in {{entityState}}, consider:
- **Incorporating as a nonprofit corporation**
- **Forming an LLC with nonprofit purpose**
- **Operating as an unincorporated association** (without legal recognition)
- **Using a fiscal sponsor** for tax-exempt activities

### 4. Professional Guidance
For your specific situation, we recommend:
- **Consulting with a local attorney** familiar with nonprofit law
- **Speaking with a CPA** about tax implications
- **Contacting your state's Secretary of State** office
- **Researching local nonprofit organizations** for examples

## How We Can Help

While we can't provide state-specific documents, we can:
- **Schedule a consultation** to discuss your options
- **Provide general UNA formation guidance**
- **Help you understand the process** even if it's different in your state
- **Connect you with resources** for your jurisdiction

## Next Steps

1. **Research your state's requirements** using the resources above
2. **Schedule a consultation** to discuss your specific needs
3. **Consider local legal counsel** for state-specific guidance
4. **Adapt the general principles** to your jurisdiction's laws

## Contact Information

**Gigi Stardust** - UNA Platform Creator
- **Email:** gigi@gigistardust.com
- **Consultation:** Available for out-of-state guidance
- **Focus:** California UNA formation and general nonprofit guidance

---

*This guide is prepared for {{entityName}} based on the information provided during intake. Since {{entityState}} is not California, you'll need to research your state's specific requirements.*`;

    // Merge template with data
    const mergedContent = mergeTemplate(template, data);
    
    // Generate PDF
    const pdfData = await generatePDF(mergedContent, `${data.entityName} - Out-of-State UNA Formation Guide`);
    
    return pdfData;
  } catch (error) {
    console.error('Error generating Out-of-State Guide:', error);
    throw new Error('Failed to generate Out-of-State Guide. Please try again.');
  }
}

// Generate LP/UNA-128 Filing Package or State-Specific Guidance
export async function generateLpUna128(data: IntakeData): Promise<Uint8Array> {
  try {
    let template = LP_UNA_128_TEMPLATE;
    let title = `${data.entityName} - LP/UNA-128 Filing Package`;
    
    // If not California, use a different template
    if (data.entityState !== 'CA') {
      template = `# STATE-SPECIFIC UNA FILING GUIDE

## For: {{entityName}}

**Organizer:** {{organizerName}}  
**Contact Email:** {{organizerEmail}}  
**Contact Phone:** {{organizerPhone}}  
**State of Formation:** {{entityState}}

## Important Note

This guide is prepared for {{entityName}} based on the information provided during intake. Since you've selected {{entityState}} (not California), the LP/UNA-128 form is not applicable.

## What You Need to Do

### 1. Research Your State's Requirements
- **State Website:** Visit your state's Secretary of State website
- **UNA Laws:** Look for Unincorporated Association statutes
- **Filing Requirements:** Check if any forms need to be filed

### 2. Common State Variations
- **Some states require no filing** for UNAs
- **Some states have different form names** (not LP/UNA-128)
- **Some states have different filing fees** and requirements

### 3. Next Steps
1. **Contact your state's Secretary of State** office
2. **Ask about UNA filing requirements** for {{entityState}}
3. **Request any necessary forms** or guidance
4. **Adapt the UNA Agreement** to your state's laws

### 4. Resources
- **{{entityState}} Secretary of State:** Search online for contact information
- **Legal Counsel:** Consider consulting with a local attorney
- **UNA Platform:** Use the core documents as a starting point

---

*This guide is prepared for {{entityName}} based on the information provided during intake. Since {{entityState}} is not California, you'll need to research your state's specific requirements.*`;
      
      title = `${data.entityName} - State-Specific UNA Filing Guide`;
    }
    
    // Merge template with data
    const mergedContent = mergeTemplate(template, data);
    
    // Generate PDF
    const pdfData = await generatePDF(mergedContent, title);
    
    return pdfData;
  } catch (error) {
    console.error('Error generating LP/UNA-128:', error);
    throw new Error('Failed to generate LP/UNA-128 Filing Package. Please try again.');
  }
}

// Generate DBA/FBN Registration Guide
export async function generateDbaGuide(data: IntakeData): Promise<Uint8Array> {
  try {
    console.log('Starting DBA Guide generation...');
    
    const template = `# DBA / FBN REGISTRATION GUIDE

## For: {{entityName}}

**Organizer:** {{organizerName}}  
**Contact Email:** {{organizerEmail}}  
**Contact Phone:** {{organizerPhone}}  
**State of Formation:** {{entityState}}  
**Date Prepared:** {{createdAt}}

---

## What is a DBA/FBN?

A **DBA (Doing Business As)** or **FBN (Fictitious Business Name)** allows your UNA to operate under a public-facing name that's different from your legal entity name.

## Why You Need This

- **Public Identity**: Operate under a memorable business name
- **Banking**: Open accounts in your business name
- **Marketing**: Use your business name in advertising
- **Legal Protection**: Establish your business identity

## California DBA/FBN Requirements

**Filing Fee:** $26 (standard across all counties)  
**Expiration:** 5 years from filing date  
**Renewal:** File renewal before expiration date

## Step-by-Step Process

### 1. Determine Your County
Your UNA is located in **{{entityState}}**. You'll need to file with your county's Clerk or Recorder office.

### 2. Prepare Required Documents
- **FBN Form**: Available from your county office
- **UNA Agreement**: Your completed association agreement
- **EIN Letter**: Your Employer Identification Number
- **LP/UNA-128 Confirmation**: California filing confirmation

### 3. File with County
- **In Person**: Visit your county clerk's office
- **By Mail**: Send completed forms with payment
- **Online**: Some counties offer online filing

### 4. Publication Requirement
Most California counties require publication in a local newspaper for 4 consecutive weeks.

### 5. Receive Certificate
After filing and publication, you'll receive your FBN certificate.

## County-Specific Information

**Your County:** {{entityState}}  
**Filing Office:** Contact your county clerk for specific forms and requirements  
**Publication Requirements:** Check with your county for newspaper requirements

## Important Notes

- **Renewal Required**: FBN expires in 5 years
- **Keep Records**: Store your FBN certificate with other UNA documents
- **Update Dashboard**: Record your FBN filing in your UNA Dashboard
- **Compliance**: Ensure ongoing compliance with renewal requirements

## Next Steps

1. **Contact your county clerk** for FBN forms
2. **Complete the filing process** within 30 days of starting business
3. **Publish in local newspaper** if required
4. **Store certificate** in your UNA document file
5. **Set renewal reminder** for 5 years from filing date

---

*This guide is prepared for {{entityName}} based on the information provided during intake. Contact your county clerk for specific filing requirements.*`;

    // Merge template with data
    const mergedContent = mergeTemplate(template, data);
    
    // Generate PDF
    const pdfData = await generatePDF(mergedContent, `${data.entityName} - DBA/FBN Registration Guide`);
    
    return pdfData;
  } catch (error) {
    console.error('Error generating DBA Guide:', error);
    throw new Error('Failed to generate DBA Guide. Please try again.');
  }
}

// Generate Financial Tracking Kit
export async function generateFinancialTrackingKit(data: IntakeData): Promise<Uint8Array> {
  try {
    console.log('Starting Financial Tracking Kit generation...');
    
    const template = `# FINANCIAL TRACKING KIT

## For: {{entityName}}

**Organizer:** {{organizerName}}  
**Contact Email:** {{organizerEmail}}  
**Contact Phone:** {{organizerPhone}}  
**State of Formation:** {{entityState}}  
**Date Prepared:** {{createdAt}}

---

## Financial Management Overview

Proper financial tracking is essential for UNA compliance, transparency, and growth. This kit provides templates and guidance for managing your UNA's finances.

## What's Included

### 1. Income & Expense Tracker
- **Monthly tracking template** for all income and expenses
- **Category organization** for better reporting
- **Year-to-date summaries** for planning

### 2. Invoice Template
- **Professional invoice format** for client billing
- **Service description fields** for clear communication
- **Payment tracking** for outstanding balances

### 3. Grant & Funding Log
- **Grant application tracking** for funding opportunities
- **Donation records** for transparency
- **Funding source analysis** for sustainability

## Financial Best Practices

### Separate Finances
- **Dedicated UNA bank account** (separate from personal)
- **Clear financial boundaries** between UNA and personal funds
- **Regular reconciliation** of accounts

### Record Keeping
- **Store all receipts** and financial documents
- **Monthly financial reviews** for compliance
- **Annual financial summaries** for planning

### Compliance Requirements
- **Track all income sources** for reporting
- **Document all expenses** with receipts
- **Maintain transparency** for members and stakeholders

## Template Downloads

### Excel/Google Sheets Templates
- **Financial Tracking Template**: Download from your Dashboard
- **Invoice Template**: Download from your Dashboard
- **Grant Tracking Template**: Download from your Dashboard

### Notion Templates (Bonus)
- **Integrated financial system** for advanced users
- **Project-based tracking** for complex UNAs
- **Team collaboration** for multiple organizers

## Setting Up Your Financial System

### 1. Choose Your Tools
- **Simple needs**: Excel/Google Sheets templates
- **Advanced needs**: Notion templates or accounting software
- **Professional needs**: QuickBooks or similar

### 2. Establish Categories
- **Income**: Grants, donations, services, memberships
- **Expenses:** Program costs, administrative, fundraising
- **Assets:** Bank accounts, equipment, property
- **Liabilities:** Loans, credit cards, accounts payable

### 3. Regular Maintenance
- **Weekly**: Record all transactions
- **Monthly**: Review and categorize
- **Quarterly**: Analyze trends and plan
- **Annually**: Comprehensive review and planning

## Financial Tools Recommendations

### Free Options
- **Wave**: Free accounting software
- **Google Sheets**: Free spreadsheet templates
- **Mint**: Free expense tracking

### Paid Options
- **QuickBooks**: Industry standard accounting
- **FreshBooks**: Simple invoicing and tracking
- **Xero**: Cloud-based accounting

### UNA-Specific Tools
- **Notion**: Customizable workspace
- **Airtable**: Database-style tracking
- **Trello**: Project-based organization

## Next Steps

1. **Download templates** from your Dashboard
2. **Set up your financial system** using recommended tools
3. **Establish regular tracking** habits
4. **Review monthly** for compliance and planning
5. **Plan quarterly** for growth and sustainability

---

*This financial tracking kit is prepared for {{entityName}} based on the information provided during intake. Customize templates to fit your specific needs.*`;

    // Merge template with data
    const mergedContent = mergeTemplate(template, data);
    
    // Generate PDF
    const pdfData = await generatePDF(mergedContent, `${data.entityName} - Financial Tracking Kit`);
    
    return pdfData;
  } catch (error) {
    console.error('Error generating Financial Tracking Kit:', error);
    throw new Error('Failed to generate Financial Tracking Kit. Please try again.');
  }
}

// Generate Client Agreement & Disclaimer
export async function generateClientAgreement(data: IntakeData): Promise<Uint8Array> {
  try {
    console.log('Starting Client Agreement generation...');
    
    const template = `# CLIENT AGREEMENT & DISCLAIMER

## For: {{entityName}}

**Organizer:** {{organizerName}}  
**Contact Email:** {{organizerEmail}}  
**Contact Phone:** {{organizerPhone}}  
**State of Formation:** {{entityState}}  
**Date Prepared:** {{createdAt}}

---

## Service Agreement

### Services Provided
By engaging UNA Consulting Services, you acknowledge that services provided are:

- **Educational guidance** on UNA formation and structure
- **Document preparation** based on your intake information
- **Template creation** customized to your specific needs
- **Dashboard access** for ongoing management and tracking
- **Referral guidance** for professional services when needed

### What We Provide
- **UNA Agreement**: Customized association agreement
- **EIN Registration Guide**: Step-by-step EIN application
- **LP/UNA-128 Filing Package**: California filing requirements
- **DBA/FBN Registration Guide**: Business name registration
- **Financial Tracking Kit**: Templates and guidance
- **Bank Account Guide**: Mission-aligned banking recommendations
- **Verification Docket**: Compliance checking and referrals

### What We Don't Provide
- **Legal advice** or attorney services
- **Tax preparation** or CPA services
- **Filing services** with government agencies
- **Ongoing compliance** management
- **Legal representation** in disputes

## Important Disclaimers

### Not a Law Firm
This platform is **not a law firm** and does not provide legal, tax, or financial advice. We provide:

- **Educational information** about UNA formation
- **Document templates** based on standard practices
- **Guidance resources** for self-directed formation
- **Referral recommendations** for professional services

### Client Responsibility
Clients remain responsible for:

- **All government filings** and compliance requirements
- **Legal review** of documents when needed
- **Tax compliance** and reporting obligations
- **Ongoing maintenance** of UNA status
- **Professional consultation** for complex scenarios

### Complex Cases
The following scenarios may require professional counsel:

- **Landholding or real estate** transfers
- **Tax-exempt status** applications (501(c)(3))
- **Fiscal sponsorship** arrangements
- **Multi-state operations** and compliance
- **Complex governance** structures
- **Grant applications** and compliance

## Verification Docket System

Our platform includes a **Verification Docket** that:

- **Automatically flags** scenarios requiring professional review
- **Provides referral guidance** to appropriate professionals
- **Estimates additional costs** for professional services
- **Ensures compliance** by identifying potential issues early

### When Referrals Are Made
- **High-priority flags** require professional review before proceeding
- **Medium-priority flags** should be considered for professional guidance
- **Low-priority flags** are optional but beneficial

## Service Limitations

### Template-Based Approach
- **Documents are templates** that require customization
- **Standard language** may not fit all situations
- **Review and modification** may be necessary
- **Professional review** recommended for complex cases

### Educational Nature
- **Services are educational** and informational
- **No attorney-client relationship** is established
- **No ongoing legal representation** is provided
- **Self-directed formation** is the approach

## Client Acknowledgment

By using this platform, you acknowledge that:

- **You understand** the educational nature of services
- **You accept responsibility** for all filings and compliance
- **You will seek professional help** when flagged by the system
- **You understand** the limitations of template-based services
- **You agree** to use services at your own risk

## Professional Referrals

When the Verification Docket flags your situation for professional review:

- **Attorney referrals** for legal matters
- **CPA referrals** for tax and accounting
- **Specialist referrals** for unique situations
- **Cost estimates** for professional services

## Contact Information

**UNA Platform Support:** gigi@gigistardust.com  
**General Questions:** Use the "Get Help" button in your Dashboard  
**Professional Referrals:** Available through the Verification Docket system

---

*This agreement establishes the terms of service between {{entityName}} and UNA Consulting Services. Please read carefully and contact us with any questions.*`;

    // Merge template with data
    const mergedContent = mergeTemplate(template, data);
    
    // Generate PDF
    const pdfData = await generatePDF(mergedContent, `${data.entityName} - Client Agreement & Disclaimer`);
    
    return pdfData;
  } catch (error) {
    console.error('Error generating Client Agreement:', error);
    throw new Error('Failed to generate Client Agreement. Please try again.');
  }
}

// Generate Bank Account Opening Guide
export async function generateBankAccountGuide(data: IntakeData): Promise<Uint8Array> {
  try {
    console.log('Starting Bank Account Guide generation...');
    
    const template = `# BANK ACCOUNT OPENING GUIDE

## For: {{entityName}}

**Organizer:** {{organizerName}}  
**Contact Email:** {{organizerEmail}}  
**Contact Phone:** {{organizerPhone}}  
**State of Formation:** {{entityState}}  
**Date Prepared:** {{createdAt}}

---

## Why a UNA Bank Account Matters

A dedicated bank account for your UNA is essential for:

- **Financial separation** from personal finances
- **Professional credibility** and transparency
- **Grant eligibility** and funding opportunities
- **Compliance requirements** and record keeping
- **Member confidence** and trust

## Required Documents

### Essential Documents
- **EIN Letter**: Your Employer Identification Number
- **UNA Agreement**: Your completed association agreement
- **LP/UNA-128 Confirmation**: California filing confirmation
- **Officer ID**: Government-issued identification
- **DBA/FBN Certificate**: If operating under business name

### Document Preparation
- **Ensure all documents** are current and complete
- **Make copies** for your records
- **Organize documents** in a professional folder
- **Bring originals** to bank appointments

## Bank Selection Strategy

### Mission-Aligned Options (Recommended)
**Credit Unions and Community Banks** are often the best choice for UNAs because they:

- **Understand community organizations** and their needs
- **Have experience** with alternative business structures
- **Offer competitive rates** and lower fees
- **Provide personalized service** and support
- **Align with UNA values** of community and cooperation

### Online Banking Options
**Modern online banks** can be excellent for UNAs that:

- **Prefer digital-first** banking experience
- **Need fast setup** and modern tools
- **Want integrations** with financial software
- **Operate primarily online** or remotely

### Traditional Banks (Use Caution)
**Large traditional banks** may:

- **Push back** on UNA structures
- **Require additional documentation** and review
- **Have higher fees** and minimum balances
- **Provide less personalized** service

## Recommended Banking Partners

### Mission-Aligned Credit Unions
- **Self-Help Credit Union**: Community development focus
- **Patelco Credit Union**: California-based, UNA experience
- **Redwood Credit Union**: North Bay area, community programs

### Affiliate Partner Banks
- **BlueVine**: Small business banking solutions
- **Mercury**: Startup and tech company banking
- **Relay**: Business banking with financial tools
- **Novo**: Entrepreneur-focused banking

## Bank Account Setup Process

### 1. Research and Compare
- **Review bank requirements** and fees
- **Compare account features** and benefits
- **Check for UNA experience** and friendliness
- **Consider location** and accessibility

### 2. Prepare Application
- **Gather all required documents**
- **Complete application forms** accurately
- **Prepare business description** and purpose
- **Plan for initial deposit** requirements

### 3. Schedule Appointment
- **Call ahead** to confirm requirements
- **Schedule in-person** meeting when possible
- **Bring all documents** and identification
- **Prepare questions** about UNA banking

### 4. Account Opening
- **Complete application** with bank representative
- **Provide all required** documentation
- **Make initial deposit** if required
- **Set up online banking** and access

### 5. Post-Setup
- **Order checks** and debit cards
- **Set up account alerts** and notifications
- **Integrate with financial** tracking system
- **Establish regular** banking habits

## Account Types to Consider

### Business Checking Account
- **Primary account** for daily operations
- **No minimum balance** requirements preferred
- **Low monthly fees** or fee waivers
- **Check writing** and debit card access

### Savings Account
- **Reserve funds** for future projects
- **Emergency funds** for unexpected expenses
- **Grant funds** awaiting disbursement
- **Higher interest rates** than checking

### Additional Services
- **Online banking** and mobile apps
- **Bill pay** and recurring payments
- **Account integration** with financial software
- **Team access** for multiple organizers

## Banking Best Practices

### Financial Separation
- **Never mix personal** and UNA finances
- **Use UNA account** for all UNA transactions
- **Keep personal expenses** in personal accounts
- **Maintain clear boundaries** between accounts

### Record Keeping
- **Save all bank statements** and documents
- **Record all transactions** in tracking system
- **Reconcile accounts** monthly
- **Maintain organized** financial records

### Compliance
- **Follow UNA agreement** requirements
- **Maintain transparency** for members
- **Prepare for annual** reviews and reporting
- **Document all financial** decisions and transactions

## Common Challenges and Solutions

### Challenge: Bank Rejection
**Solution**: 
- **Try credit unions** and community banks first
- **Explain UNA structure** clearly to representatives
- **Provide all required** documentation
- **Consider online banks** as alternatives

### Challenge: High Fees
**Solution**:
- **Compare multiple** banking options
- **Look for fee waivers** and discounts
- **Consider credit unions** with lower fees
- **Negotiate fees** based on relationship

### Challenge: Limited Services
**Solution**:
- **Use multiple accounts** for different needs
- **Integrate with financial** software tools
- **Consider hybrid approach** with multiple banks
- **Plan for future** banking needs

## Next Steps

1. **Review recommended banks** and their requirements
2. **Gather all required** documents and identification
3. **Contact preferred banks** to confirm UNA acceptance
4. **Schedule appointments** with multiple banks if needed
5. **Complete account setup** with chosen bank
6. **Integrate with financial** tracking system
7. **Establish regular** banking and record-keeping habits

## Resources and Support

### UNA Platform Support
- **Dashboard guidance** for banking setup
- **Document templates** for bank applications
- **Verification system** for compliance checking
- **Referral system** for professional guidance

### Professional Support
- **Banking consultants** for complex situations
- **Legal review** for unusual structures
- **CPA guidance** for tax implications
- **Specialist support** for unique needs

---

*This guide is prepared for {{entityName}} based on the information provided during intake. Contact recommended banks directly for current requirements and fees.*`;

    // Merge template with data
    const mergedContent = mergeTemplate(template, data);
    
    // Generate PDF
    const pdfData = await generatePDF(mergedContent, `${data.entityName} - Bank Account Opening Guide`);
    
    return pdfData;
  } catch (error) {
    console.error('Error generating Bank Account Guide:', error);
    throw new Error('Failed to generate Bank Account Guide. Please try again.');
  }
}

// Generate all documents in sequence
export async function generateAllDocuments(data: IntakeData): Promise<{
  unaAgreement: Uint8Array;
  einGuide: Uint8Array;
  lpUna128: Uint8Array;
}> {
  try {
    const [unaAgreement, einGuide, lpUna128] = await Promise.all([
      generateUnaAgreement(data),
      generateEinGuide(data),
      generateLpUna128(data)
    ]);

    return {
      unaAgreement,
      einGuide,
      lpUna128
    };
  } catch (error) {
    console.error('Error generating documents:', error);
    throw new Error('Failed to generate one or more documents. Please try again.');
  }
}

// Generate DOCX versions of documents
export async function generateUnaAgreementDOCX(data: IntakeData): Promise<Uint8Array> {
  try {
    const mergedContent = mergeTemplate(UNA_AGREEMENT_TEMPLATE, data);
    return await generateDOCX(mergedContent, `${data.entityName} - UNA Agreement`);
  } catch (error) {
    console.error('Error generating UNA Agreement DOCX:', error);
    throw new Error('Failed to generate UNA Agreement DOCX. Please try again.');
  }
}

export async function generateEinGuideDOCX(data: IntakeData): Promise<Uint8Array> {
  try {
    const mergedContent = mergeTemplate(EIN_GUIDE_TEMPLATE, data);
    return await generateDOCX(mergedContent, `${data.entityName} - EIN Registration Guide`);
  } catch (error) {
    console.error('Error generating EIN Guide DOCX:', error);
    throw new Error('Failed to generate EIN Guide DOCX. Please try again.');
  }
}

export async function generateLpUna128DOCX(data: IntakeData): Promise<Uint8Array> {
  try {
    const mergedContent = mergeTemplate(LP_UNA_128_TEMPLATE, data);
    return await generateDOCX(mergedContent, `${data.entityName} - LP-UNA-128 Filing Package`);
  } catch (error) {
    console.error('Error generating LP/UNA-128 DOCX:', error);
    throw new Error('Failed to generate LP/UNA-128 Filing Package DOCX. Please try again.');
  }
}

// New: Generate comprehensive formation guide
export async function generateComprehensiveFormationGuide(data: IntakeData): Promise<Uint8Array> {
  try {
    const comprehensiveTemplate = `# COMPREHENSIVE UNA FORMATION GUIDE

**Organization:** {{entityName}}  
**Organizer:** {{organizerName}}  
**Generated:** ${new Date().toLocaleDateString()}  
**Platform:** UNA Formation Done Right

---

## EXECUTIVE SUMMARY

This comprehensive guide provides everything you need to successfully form and operate your Unincorporated Association (UNA) in California. It consolidates all essential information, requirements, and next steps into one document.

---

## SECTION 1: ORGANIZATION OVERVIEW

### 1.1 Basic Information
**Entity Name:** {{entityName}}  
**Purpose:** {{entityPurpose}}  
**Activities:** {{entityActivities}}  
**Formation State:** {{entityState}}  
**Start Date:** {{entityStartDate}}

### 1.2 Organizer Details
**Primary Organizer:** {{organizerName}}  
**Role:** {{organizerRole}}  
**Contact:** {{organizerEmail}} | {{organizerPhone}}  
**Address:** {{organizerAddress}}, {{organizerCity}}, {{organizerState}} {{organizerZip}}

### 1.3 Mailing Address
**Official Address:** {{mailingAddress}}, {{mailingCity}}, {{mailingState}} {{mailingZip}}, {{mailingCountry}}

---

## SECTION 2: LEGAL STRUCTURE & COMPLIANCE

### 2.1 Governance Structure
**Leadership Framework:** {{leadershipStructure}}  
**Family Leadership:** {{familyLeadership}}  
**Conflict of Interest Policies:** {{conflictOfInterest}}  
**Succession Planning:** {{successionPlanning}}

### 2.2 Tax & Compliance Requirements
**EIN Required:** {{needsEIN}}  
**Tax-Exempt Intent:** {{taxExemptIntent}}  
**Fiscal Sponsorship:** {{fiscalSponsorship}}  
**Interstate Activity:** {{interstateActivity}}  
**States of Operation:** {{statesOfOperation}}

### 2.3 Compliance Notes
{{complianceNotes}}

---

## SECTION 3: OPERATIONAL PLANNING

### 3.1 Financial & Property Plans
**Property Plans:** {{propertyPlans}}  
**Grant Plans:** {{grantPlans}}  
**Fundraising Activities:** {{fundraisingPlans}}

### 3.2 Organizational Identity
**Has Insignia:** {{hasInsignia}}  
**Insignia Description:** {{insigniaDescription}}

---

## SECTION 4: IMMEDIATE NEXT STEPS

### 4.1 Week 1: Foundation
- [ ] Review and sign UNA Agreement
- [ ] Apply for EIN (if required)
- [ ] Set up organizational email and phone
- [ ] Create basic financial tracking system

### 4.2 Week 2: Banking & Financial
- [ ] Open business bank account
- [ ] Set up financial management tools
- [ ] Establish basic bookkeeping
- [ ] Consider fiscal sponsorship if needed

### 4.3 Week 3: Operations
- [ ] Develop operational procedures
- [ ] Set up record-keeping systems
- [ ] Establish communication protocols
- [ ] Plan first activities or programs

### 4.4 Week 4: Compliance & Growth
- [ ] Review compliance requirements
- [ ] Plan for tax-exempt status if applicable
- [ ] Develop fundraising strategy
- [ ] Establish monitoring and evaluation

---

## SECTION 5: PROFESSIONAL RESOURCES

### 5.1 Legal Professionals
- **Nonprofit Attorney:** For complex legal structures
- **Real Estate Attorney:** If property management involved
- **Tax Attorney:** For tax-exempt status applications

### 5.2 Financial Professionals
- **CPA/Tax Advisor:** For tax compliance and planning
- **Bookkeeper:** For financial record management
- **Financial Advisor:** For investment and growth planning

### 5.3 Operational Support
- **Nonprofit Consultant:** For organizational development
- **Fundraising Specialist:** For revenue development
- **Technology Consultant:** For systems and tools

---

## SECTION 6: COMPLIANCE CHECKLIST

### 6.1 Ongoing Requirements
- [ ] Maintain accurate financial records
- [ ] Keep organizational documents current
- [ ] Monitor compliance with state requirements
- [ ] Update information as organization evolves

### 6.2 Annual Tasks
- [ ] Review and update UNA Agreement
- [ ] Assess organizational performance
- [ ] Plan for next year's activities
- [ ] Review compliance status

---

## SECTION 7: RISK MANAGEMENT

### 7.1 Insurance Considerations
- **General Liability Insurance:** For organizational activities
- **Directors & Officers Insurance:** For leadership protection
- **Property Insurance:** If holding real property
- **Professional Liability:** For specialized services

### 7.2 Legal Protection
- **Clear Policies & Procedures:** Document all processes
- **Regular Legal Review:** Annual compliance check
- **Professional Consultation:** For complex decisions
- **Documentation:** Keep records of all decisions

---

## SECTION 8: SUCCESS METRICS

### 8.1 Organizational Health
- Mission alignment and impact
- Financial sustainability
- Community engagement
- Operational efficiency

### 8.2 Growth Indicators
- Program expansion
- Revenue diversification
- Community recognition
- Partnership development

---

## IMPORTANT DISCLAIMERS

**Legal Compliance:** This guide provides general information and should not replace professional legal, tax, or financial advice.

**State Requirements:** California UNA requirements may change. Verify current requirements with legal professionals.

**Professional Guidance:** For complex situations, high-risk activities, or compliance questions, consult qualified professionals.

---

## SUPPORT & RESOURCES

**Platform Support:** UNA Formation Done Right provides ongoing guidance and resources.

**Professional Network:** Connect with our network of UNA formation professionals.

**Community:** Join our community of UNA organizers for support and best practices.

---

*Generated by UNA Formation Done Right - Professional UNA Formation Services*  
*For ongoing support and professional guidance, visit our platform or schedule a consultation.*`;

    const content = mergeTemplate(comprehensiveTemplate, data);
    return await generatePDF(content, 'Comprehensive-Formation-Guide');
  } catch (error) {
    console.error('Error generating comprehensive formation guide:', error);
    throw new Error('Failed to generate comprehensive formation guide');
  }
}
